runtime: nodejs16

env: standard

service: perfarm-experience

runtime_config:
  runtime_version: 16.20.0

instance_class: B4_1G

manual_scaling:
  instances: 3

resources:
  cpu: 3
  memory_gb: 5
  disk_size_gb: 20

env_variables:
  FIREBASE_APP_KEY: AIzaSyCr1V2KwIlYmteUOOtG4FvdjqXVjirGKiM
  FIREBASE_AUTH_DOMAIN: perfarm-experience.firebaseapp.com
  FIREBASE_PROJECT_ID: perfarm-experience
  FIREBASE_STORAGE_BUCCKET: perfarm-experience.appspot.com
  FIREBASE_MESSAGING_SENDER_ID: 264367941327
  FIREBASE_APP_ID: 1:264367941327:web:9a1bc3de749d800d63f9ba
  FIREBASE_DATABASE_URL: https://perfarm-experience-default-rtdb.firebaseio.com
  JWT_SECRET: pex-abcd
